Bag of Words

In [2]:
from mluvisuals import *
BagOfWords()

In [4]:
!pip install torch==1.13.1
!pip install torchtext==0.14.1
!pip install mxnet==1.9.1
!pip install gluonnlp==0.9.1 
!pip install nltk==3.8.1
!pip install pandas==1.1.5
!pip install scikit-learn==1.0.0
!pip install numpy==1.22.2
!pip install matplotlib==3.3.4
!pip install seaborn==0.11.2
!pip install jupyter-server==2.1.0
!pip install ipykernel==6.20.2

ERROR: Could not find a version that satisfies the requirement mxnet==1.9.1 (from versions: 0.11.0, 0.12.0, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.1.0.post0, 1.2.0, 1.2.1, 1.2.1.post1, 1.3.0, 1.3.1, 1.4.0, 1.4.0.post0, 1.4.1, 1.5.0, 1.6.0, 1.7.0.post1, 1.7.0.post2)
ERROR: No matching distribution found for mxnet==1.9.1


  Using cached gluonnlp-0.9.1.tar.gz (252 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for gluonnlp
Failed to build gluonnlp


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [115 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\gluonnlp
  copying src\gluonnlp\base.py -> build\lib.win-amd64-cpython-310\gluonnlp
  copying src\gluonnlp\_constants.py -> build\lib.win-amd64-cpython-310\gluonnlp
  copying src\gluonnlp\__init__.py -> build\lib.win-amd64-cpython-310\gluonnlp
  creating build\lib.win-amd64-cpython-310\gluonnlp\calibration
  copying src\gluonnlp\calibration\collector.py -> build\lib.win-amd64-cpython-310\gluonnlp\calibration
  copying src\gluonnlp\calibration\__init__.py -> build\lib.win-amd64-cpython-310\gluonnlp\calibration
  creating build\lib.win-amd64-cpython-310\gluonnlp\data
  copying src\gluonnlp\data\candidate_sampler.py -> build\lib.win-amd64-cpython-310\gluonnlp\data
  copying src\gluonnlp\data\con

  Using cached pandas-1.1.5.tar.gz (5.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: still running...
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Failed to build pandas


  error: subprocess-exited-with-error
  
  exit code: 1
  
  [1155 lines of output]
  <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  <string>:45: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pandas
  copying pandas\conftest.py -> build\lib.win-amd64-cpython-310\pandas
  copying pandas\testing.py -> build\lib.win-amd64-cpython-310\pandas
  copying pandas\_testing.py -> build\lib.win-amd64-cpython-310\pandas
  copying pandas\_typing.py -> build\lib.win-amd64-cpython-310\pandas
  copying pandas\_version.py -> build\lib.win-amd64-cpython-310\pandas
  copying pandas\__init__.py -> build\lib.win-amd64-cpython-310\pandas
  creating build\lib.win-amd64-cpython-310\pandas\api
  copying pandas\api\__init__

  Using cached scikit-learn-1.0.tar.gz (7.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [43 lines of output]
  Partial import of sklearn during the build process.
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  Traceback (most recent call last):
    File "C:\Users\Asus\anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\Asus\anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Asus\anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\Asus\AppData\Local\Temp\pip-build-env-ff176xic\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in p

  Using cached matplotlib-3.3.4.tar.gz (37.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for matplotlib
Failed to build matplotlib


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [573 lines of output]
  
  Edit setup.cfg to change the build options; suppress output with --quiet.
  
  BUILDING MATPLOTLIB
    matplotlib: yes [3.3.4]
        python: yes [3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023,
                    18:18:15) [MSC v.1916 64 bit (AMD64)]]
      platform: yes [win32]
   sample_data: yes [installing]
         tests: no  [skipping due to configuration]
        macosx: no  [Mac OS-X only]
  
  C:\Users\Asus\anaconda\lib\site-packages\setuptools\dist.py:285: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated, consider using implicit namespaces instead (PEP 420).
    warnings.warn(msg, SetuptoolsDeprecationWarning)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  copying lib\pylab.py -> build\lib.win-amd64-cpython-310
  creating b

  Using cached jupyter_server-2.1.0-py3-none-any.whl (365 kB)
  Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
  Using cached jupyter_events-0.9.0-py3-none-any.whl (18 kB)
  Using cached jupyter_server_terminals-0.5.1-py3-none-any.whl (13 kB)
  Using cached pyzmq-25.1.2-cp310-cp310-win_amd64.whl (1.2 MB)
  Using cached jsonschema-4.21.0-py3-none-any.whl (85 kB)
  Using cached python_json_logger-2.0.7-py3-none-any.whl (8.1 kB)
  Using cached referencing-0.32.1-py3-none-any.whl (26 kB)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
  Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
  Using cached jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
  Using cached rpds_py-0.17.1-cp310-none-win_amd64.whl (205 kB)
  Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
  Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
  Attempting uninstall: pyzmq
    Found existing instal

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Asus\\anaconda\\Lib\\site-packages\\~mq\\backend\\cython\\context.cp310-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [5]:
from sklearn.feature_extraction.text import CountVectorizer
sentences = ["This document is the first document",
             "This document is the second document",
             "and this is the third one"]
binary_vectorizer=CountVectorizer(binary=True)
x=binary_vectorizer.fit_transform(sentences)

In [6]:
x.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [8]:
binary_vectorizer.vocabulary_

{'this': 8,
 'document': 1,
 'is': 3,
 'the': 6,
 'first': 2,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}

In [10]:
print(binary_vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [11]:
new_sentence=['This is the new sentence']
new_vectors=binary_vectorizer.transform(new_sentence)

In [12]:
new_vectors.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer 
sentences = ["This document is the first document", "This document is the second document", "and this is the third one"]
count_vectorizer = CountVectorizer()
xc = count_vectorizer.fit_transform(sentences)
xc.toarray()

array([[0, 2, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [14]:
new_sentence = ["This is the new sentence"]
new_vectors = count_vectorizer.transform(new_sentence)
new_vectors.toarray()

array([[0, 0, 0, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
sentences = ["This document is the first document",
             "This document is the second document",
             "and this is the third one"]
xf=tfidf_vectorizer.fit_transform(sentences)
xf.toarray()

array([[0.        , 0.7284449 , 0.47890875, 0.28285122, 0.        ,
        0.        , 0.28285122, 0.        , 0.28285122],
       [0.        , 0.7284449 , 0.        , 0.28285122, 0.        ,
        0.47890875, 0.28285122, 0.        , 0.28285122],
       [0.49711994, 0.        , 0.        , 0.29360705, 0.49711994,
        0.        , 0.29360705, 0.49711994, 0.29360705]])

In [16]:
new_sentence=["This is the new sentence"]
new_vectors=tfidf_vectorizer.transform(new_sentence)
new_vectors.toarray()

array([[0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027, 0.        , 0.57735027]])

In [17]:
tfidf_vectorizer.idf_

array([1.69314718, 1.28768207, 1.69314718, 1.        , 1.69314718,
       1.69314718, 1.        , 1.69314718, 1.        ])

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
sentences = ["This document is the first document",
             "This document is the second document",
             "and this is the third one"]
tfidf_vectorizer=TfidfVectorizer()
xf=tfidf_vectorizer.fit_transform(sentences)
xf.toarray()


array([[0.        , 0.7284449 , 0.47890875, 0.28285122, 0.        ,
        0.        , 0.28285122, 0.        , 0.28285122],
       [0.        , 0.7284449 , 0.        , 0.28285122, 0.        ,
        0.47890875, 0.28285122, 0.        , 0.28285122],
       [0.49711994, 0.        , 0.        , 0.29360705, 0.49711994,
        0.        , 0.29360705, 0.49711994, 0.29360705]])